<?php

namespace Database\Seeders;

use App\Models\TravelInfoItem;
use Illuminate\Database\Seeder;

class TravelInfoItemSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data to avoid duplicates
        TravelInfoItem::truncate();

        // ============================================================
        // CULTURE (type: culture) — 6 items, no category_key
        // ============================================================
        $cultureItems = [
            [
                'title' => 'TARIAN KABASARAN',
                'title_en' => 'KABASARAN DANCE',
                'title_ko' => '카바사란 전쟁 춤',
                'title_zh' => '卡巴萨兰战舞',
                'description' => 'Kabasaran adalah tarian perang Minahasa, diiringi suara tambur/gong kecil. Tarian ini sekarang menjadi tarian penyambutan tamu kehormatan.',
                'description_en' => 'Kabasaran is war dance of Minahasa, accompanied by the sound of Tambour/small gong. This dance is now a welcoming dance for honored guests.',
                'description_ko' => '카바사란은 미나하사의 전쟁 춤으로, 작은 징/탬버의 소리에 맞춰 춤을 춥니다.',
                'description_zh' => '卡巴萨兰是米纳哈萨的战舞，伴随着小锣鼓的声音。',
                'sort_order' => 1,
            ],
            [
                'title' => 'TARIAN KATRILI',
                'title_en' => 'KATRILI DANCE',
                'title_ko' => '카트릴리 춤',
                'title_zh' => '卡特里利舞蹈',
                'description' => 'Katrili adalah tarian warisan kolonial Portugis dan Spanyol sejak abad ke-16 yang ditarikan dengan ceria. Tarian ini sering dibawakan dalam acara resmi pemerintah dan festival budaya.',
                'description_en' => 'Katrili is a Heritage dance of Portuguese and Spanish Colonial since 16th century ago. This dance is often performed at official government events and cultural festivals.',
                'description_ko' => '카트릴리는 16세기 포르투갈과 스페인 식민지 시대의 유산 춤입니다.',
                'description_zh' => '卡特里利是16世纪葡萄牙和西班牙殖民时期的遗产舞蹈。',
                'sort_order' => 2,
            ],
            [
                'title' => 'TARIAN MAENGKET',
                'title_en' => 'MAENGKET DANCE',
                'title_ko' => '마엥켓 춤',
                'title_zh' => '马恩凯特舞蹈',
                'description' => 'Tarian tradisional asli Minahasa yang dilakukan saat panen raya dengan gerakan sederhana namun penuh makna syukur.',
                'description_en' => 'Maengket is an original traditional dance of Minahasa which is performed while harvesting crops with simple yet meaningful gratitude movements.',
                'description_ko' => '마엥켓은 수확 시 수행되는 미나하사의 전통 춤입니다.',
                'description_zh' => '马恩凯特是米纳哈萨的传统舞蹈，在丰收时表演。',
                'sort_order' => 3,
            ],
            [
                'title' => 'MUSIK KOLINTANG',
                'title_en' => 'KOLINTANG MUSIC',
                'title_ko' => '콜린탕 음악',
                'title_zh' => '科林塘音乐',
                'description' => 'Musik tradisional Minahasa yang terbuat dari kayu yang menghasilkan suara unik, sering dimainkan di pesta pernikahan dan upacara adat.',
                'description_en' => 'Kolintang is traditional Minahasa music made of wood that can produce unique musical sound, often played at weddings and traditional ceremonies.',
                'description_ko' => '콜린탕은 나무로 만든 미나하사 전통 음악으로 독특한 소리를 냅니다.',
                'description_zh' => '科林塘是米纳哈萨用木头制成的传统音乐，能产生独特的声音。',
                'sort_order' => 4,
            ],
            [
                'title' => 'PANTAI MALALAYANG',
                'title_en' => 'MALALAYANG BEACH',
                'title_ko' => '말라라양 해변',
                'title_zh' => '马拉拉扬海滩',
                'description' => 'Pantai pasir hitam dengan pemandangan Pulau Manado Tua dan Bunaken. Tempat populer untuk menikmati pisang goreng saat matahari terbenam.',
                'description_en' => 'This black sand beach has the beautiful view of Manado Tua Island, Bunaken Island, even Siladen Island. A popular spot to enjoy fried bananas at sunset.',
                'description_ko' => '마나도 투아 섬과 부나켄 섬의 아름다운 전망이 있는 검은 모래 해변입니다.',
                'description_zh' => '这片黑沙海滩可以看到美纳多老岛和布纳肯岛的美丽景色。',
                'sort_order' => 5,
            ],
            [
                'title' => 'PATUNG YESUS MEMBERKATI',
                'title_en' => 'STATUE OF JESUS BLESSING',
                'title_ko' => '예수 축복 동상',
                'title_zh' => '耶稣祝福雕像',
                'description' => 'Patung Yesus Memberkati di Manado adalah yang terbesar ke-1 di Asia dan ke-3 di dunia. Menjadi ikon baru Kota Manado sejak 2007.',
                'description_en' => 'Statue of Jesus Blessing in Manado is the 1st biggest in Asia & the 3rd biggest in the world. It has been a new icon of Manado City since 2007.',
                'description_ko' => '마나도의 예수 축복 동상은 아시아에서 가장 크고 세계에서 세 번째로 큽니다.',
                'description_zh' => '美纳多的耶稣祝福雕像是亚洲最大的，世界第三大的。',
                'sort_order' => 6,
            ],
        ];

        foreach ($cultureItems as $item) {
            TravelInfoItem::create(array_merge($item, [
                'type' => 'culture',
                'category_key' => null,
                'is_active' => true,
            ]));
        }

        // ============================================================
        // FOOD (type: food) — grouped by category_key
        // ============================================================
        $foodItems = [
            // === Main Menu ===
            ['category_key' => 'main', 'sort_order' => 1,
                'title' => 'Seafood', 'title_en' => 'Seafood', 'title_ko' => '해산물', 'title_zh' => '海鲜',
                'description' => 'Seafood segar adalah makanan pokok di Manado. Favoritnya termasuk Udang Gala Bakar dan Kerapu Bakar Pedas, biasanya disajikan dengan Sambal Dabu-Dabu.',
                'description_en' => 'Fresh seafood is a staple in Manado. Favorites include Grilled Gala Shrimp and Grilled Spicy Grouper, typically served with Sambal Dabu-Dabu.',
                'description_ko' => '신선한 해산물은 마나도의 주식입니다. 삼발 다부다부와 함께 제공됩니다.',
                'description_zh' => '新鲜海鲜是美纳多的主食。通常配以参巴酱。',
            ],
            ['category_key' => 'main', 'sort_order' => 2,
                'title' => 'Kepiting Kenari', 'title_en' => 'Coconut Crab', 'title_ko' => '코코넛 크랩', 'title_zh' => '椰子蟹',
                'description' => 'Arthropoda darat terbesar, dianggap sebagai hidangan mewah dengan rasa mirip lobster. Tersedia dalam Saus Padang, Saus Tiram, atau Saus Santan.',
                'description_en' => 'The largest land-living arthropod, considered a delicacy with a taste similar to lobster. Available in Padang Spicy, Oyster, or Coconut Milk Sauce.',
                'description_ko' => '가장 큰 육지 절지동물로, 랍스터와 비슷한 맛의 진미입니다.',
                'description_zh' => '最大的陆生节肢动物，被认为是美味佳肴，味道类似龙虾。',
            ],
            ['category_key' => 'main', 'sort_order' => 3,
                'title' => 'Ikan Woku Belanga', 'title_en' => 'Ikan Woku Belanga', 'title_ko' => '이칸 워쿠 벨랑가', 'title_zh' => '锅焖香料鱼',
                'description' => 'Ikan kerapu yang dimasak dalam belanga dengan rempah melimpah seperti kemangi, daun kunyit, serai, tomat, dan cabai yang sangat pedas.',
                'description_en' => 'Grouper fish cooked in a pot with rich spices like lemon basil, turmeric leaf, lemongrass, tomato, and blazingly spicy chili peppers.',
                'description_ko' => '레몬 바질, 강황 잎, 레몬그라스 등 풍부한 향신료로 냄비에 조리한 그루퍼.',
                'description_zh' => '用丰富的香料如柠檬罗勒、姜黄叶、香茅等在锅中烹制的石斑鱼。',
            ],
            ['category_key' => 'main', 'sort_order' => 4,
                'title' => 'Cakalang Pampis', 'title_en' => 'Cakalang Pampis', 'title_ko' => '참치 플로스', 'title_zh' => '�的旗鱼松',
                'description' => 'Ikan cakalang suwir khas Manado, cocok dinikmati dengan nasi hangat atau sebagai isian Panada.',
                'description_en' => 'Shredded Skipjack Tuna (Tuna Floss) ala Manado, perfect with warm rice or as a filling for Panada.',
                'description_ko' => '마나도 스타일의 참치 플로스, 따뜻한 밥과 완벽한 조합.',
                'description_zh' => '美纳多风格的大目金枪鱼松，配温热米饭完美搭配。',
            ],
            ['category_key' => 'main', 'sort_order' => 5,
                'title' => 'Kuah Asam', 'title_en' => 'Kuah Asam', 'title_ko' => '쿠아 아삼', 'title_zh' => '酸汤',
                'description' => 'Sup ikan asam yang segar dan bergizi menggunakan kakap merah atau ikan lainnya, dibumbui dengan tomat dan jeruk nipis.',
                'description_en' => 'A fresh and nutritious sour fish soup using red snapper or other fish, flavored with tomatoes and lemon juice.',
                'description_ko' => '적어나 다른 생선을 사용한 신선하고 영양가 있는 신 생선 수프.',
                'description_zh' => '使用鲷鱼或其他鱼制成的新鲜营养酸鱼汤。',
            ],
            ['category_key' => 'main', 'sort_order' => 6,
                'title' => 'Ikan Tude Woku Daun', 'title_en' => 'Ikan Tude Woku Daun', 'title_ko' => '이칸 투데 워쿠 다운', 'title_zh' => '香叶鱼',
                'description' => 'Ikan Tude segar yang dibungkus daun pisang dan dimasak dengan banyak rempah lokal.',
                'description_en' => 'Fresh Tude fish wrapped in banana leaves and cooked with an abundance of local spices.',
                'description_ko' => '바나나 잎으로 감싸고 지역 향신료와 함께 조리한 신선한 투데 생선.',
                'description_zh' => '用香蕉叶包裹并配以丰富当地香料烹制的新鲜鱼。',
            ],
            ['category_key' => 'main', 'sort_order' => 7,
                'title' => 'Rica Ikan Roa (Sambel Roa)', 'title_en' => 'Rica Ikan Roa (Sambel Roa)', 'title_ko' => '삼발 로아', 'title_zh' => '辣椒烟熏鱼',
                'description' => 'Ikan Roa asap dicampur dengan cabai dan tomat. Biasanya disajikan dengan Tinutuan atau pisang goreng.',
                'description_en' => 'Smoked Roa fish mixed with chili and tomatoes. Usually served with Tinutuan or fried plantains.',
                'description_ko' => '칠리와 토마토를 섞은 훈제 로아 생선. 보통 티누투안이나 튀긴 바나나와 함께 제공됩니다.',
                'description_zh' => '烟熏鱼与辣椒和番茄混合。通常配以粥或炸香蕉。',
            ],

            // === Breakfast Menu ===
            ['category_key' => 'breakfast', 'sort_order' => 1,
                'title' => 'Tinutuan (Bubur Manado)', 'title_en' => 'Tinutuan (Bubur Manado)', 'title_ko' => '마나도 죽', 'title_zh' => '美纳多粥',
                'description' => 'Bubur sehat dari beras, bayam, singkong, labu, dan jagung. Sering disajikan dengan keripik Nike atau cakalang goreng.',
                'description_en' => 'A healthy porridge made from rice, spinach, cassava, pumpkin, and corn. Often served with Nike savory chips or fried Cakalang.',
                'description_ko' => '쌀, 시금치, 카사바, 호박, 옥수수로 만든 건강한 죽.',
                'description_zh' => '由大米、菠菜、木薯、南瓜和玉米制成的健康粥。',
            ],
            ['category_key' => 'breakfast', 'sort_order' => 2,
                'title' => 'Nasi Kuning', 'title_en' => 'Nasi Kuning (Yellow Rice)', 'title_ko' => '노란 쌀밥', 'title_zh' => '黄饭',
                'description' => 'Nasi yang dimasak dengan santan dan kunyit, disajikan dengan cakalang suwir, daging sapi, dan telur rebus, dibungkus daun woka.',
                'description_en' => 'Rice cooked with coconut milk and turmeric, served with shredded cakalang, beef, and boiled egg, traditionally wrapped in palm leaves.',
                'description_ko' => '코코넛 밀크와 강황으로 요리한 쌀, 참치 플로스, 쇠고기, 삶은 달걀과 함께 제공.',
                'description_zh' => '用椰奶和姜黄烹制的米饭，配以鱼松、牛肉和煮鸡蛋。',
            ],

            // === Dessert & Snacks ===
            ['category_key' => 'dessert', 'sort_order' => 1,
                'title' => 'Klappertart', 'title_en' => 'Klappertart', 'title_ko' => '클라퍼타르트', 'title_zh' => '椰子派',
                'description' => 'Kue kelapa legendaris dari kelapa muda, susu, vanila, dengan topping kismis, kenari, atau keju.',
                'description_en' => 'A legendary coconut cake made with young coconut, milk, vanilla, and toppings like raisins, walnuts, or cheese.',
                'description_ko' => '어린 코코넛, 우유, 바닐라로 만든 전설적인 코코넛 케이크.',
                'description_zh' => '用嫩椰子、牛奶、香草制成的传奇椰子蛋糕。',
            ],
            ['category_key' => 'dessert', 'sort_order' => 2,
                'title' => 'Es Kacang Merah', 'title_en' => 'Es Kacang Merah', 'title_ko' => '팥 빙수', 'title_zh' => '红豆刨冰',
                'description' => 'Campuran segar kacang merah dan buah-buahan yang disajikan dengan es serut—pilihan sempurna bagi pecinta kacang merah.',
                'description_en' => 'A refreshing mix of red beans and fruits served on shaved ice—a perfect treat for red bean lovers.',
                'description_ko' => '팥과 과일을 갈아 만든 빙수—팥 애호가에게 완벽한 간식.',
                'description_zh' => '红豆和水果的清爽混合，配以刨冰——红豆爱好者的完美选择。',
            ],
            ['category_key' => 'dessert', 'sort_order' => 3,
                'title' => 'Pisang Goreng', 'title_en' => 'Fried Banana (Pisang Goreng)', 'title_ko' => '바나나 튀김', 'title_zh' => '炸香蕉',
                'description' => 'Kebiasaan unik orang Manado: menikmati pisang goreng renyah dengan dicocol sambal pedas.',
                'description_en' => 'A unique Manadonese habit: enjoying crispy fried bananas dipped in spicy chili paste (sambal).',
                'description_ko' => '독특한 마나도 습관: 바삭한 바나나 튀김을 매운 삼발에 찍어 먹기.',
                'description_zh' => '独特的美纳多习惯：将酥脆的炸香蕉蘸辣椒酱吃。',
            ],
            ['category_key' => 'dessert', 'sort_order' => 4,
                'title' => 'Panada', 'title_en' => 'Panada', 'title_ko' => '파나다', 'title_zh' => '帕纳达',
                'description' => 'Camilan populer mirip empanada, diisi dengan ikan cakalang suwir pedas.',
                'description_en' => 'A popular snack similar to empanadas, filled with spicy shredded Skipjack tuna.',
                'description_ko' => '매운 참치 플로스로 채운 엠파나다와 비슷한 인기 간식.',
                'description_zh' => '类似于馅饼的热门零食，里面填满了辣味金枪鱼。',
            ],
            ['category_key' => 'dessert', 'sort_order' => 5,
                'title' => 'Lalampa', 'title_en' => 'Lalampa', 'title_ko' => '랄람파', 'title_zh' => '糯米卷',
                'description' => 'Ketan gulung tradisional diisi ikan cakalang suwir, mirip lemper tapi dengan rasa pedas yang khas.',
                'description_en' => 'Traditional glutinous rice rolls filled with shredded tuna, similar to lemper but with a distinct spicy kick.',
                'description_ko' => '참치 가루를 채운 전통 찹쌀 롤, 매운맛이 일품.',
                'description_zh' => '传统糯米卷，里面填满了碎金枪鱼，带有独特的辣味。',
            ],

            // === Drinks ===
            ['category_key' => 'drinks', 'sort_order' => 1,
                'title' => 'Cap Tikus', 'title_en' => 'Cap Tikus', 'title_ko' => '캡 티쿠스', 'title_zh' => '鼠牌酒',
                'description' => 'Minuman beralkohol tradisional dari nira pohon palem (saguer), minuman khas wilayah Minahasa.',
                'description_en' => 'A traditional high-alcohol drink processed from palm tree sap (saguer), a signature spirit of the Minahasa region.',
                'description_ko' => '야자수 수액으로 만든 전통 고도주, 미나하사 지역의 대표 술.',
                'description_zh' => '由棕榈树汁酿制的传统高度酒，是米纳哈萨地区的标志性烈酒。',
            ],
        ];

        foreach ($foodItems as $item) {
            TravelInfoItem::create(array_merge($item, [
                'type' => 'food',
                'is_active' => true,
            ]));
        }

        // ============================================================
        // SHOPPING (type: shopping) — grouped by category_key
        // ============================================================
        $shoppingItems = [
            // === City Shopping Center ===
            ['category_key' => 'center', 'sort_order' => 1,
                'title' => 'Mega Mall', 'title_en' => 'Mega Mall', 'title_ko' => '메가 몰', 'title_zh' => '大型购物中心',
                'description' => 'Mall pertama di Manado yang dibangun tahun 2004, menyediakan kebutuhan keluarga dalam satu tempat.',
                'description_en' => 'The first mall in Manado built in 2004, providing various family needs in one place.',
                'description_ko' => '2004년에 건설된 마나도 최초의 쇼핑몰.',
                'description_zh' => '2004年建成的美纳多第一家购物中心。',
            ],
            ['category_key' => 'center', 'sort_order' => 2,
                'title' => 'Manado Town Square (Mantos)', 'title_en' => 'Manado Town Square (Mantos)', 'title_ko' => '마나도 타운 스퀘어', 'title_zh' => '美纳多城市广场',
                'description' => 'Pusat perbelanjaan paling lengkap dengan berbagai branded shop, restoran, dan hiburan.',
                'description_en' => 'The most complete shopping center with various branded shops, restaurants, and entertainment.',
                'description_ko' => '다양한 브랜드 매장, 레스토랑, 엔터테인먼트가 있는 가장 완벽한 쇼핑센터.',
                'description_zh' => '拥有各种品牌商店、餐厅和娱乐设施的最完整购物中心。',
            ],
            ['category_key' => 'center', 'sort_order' => 3,
                'title' => 'IT Center Manado', 'title_en' => 'IT Center Manado', 'title_ko' => 'IT 센터 마나도', 'title_zh' => 'IT中心美纳多',
                'description' => 'Pusat elektronik, handphone, dan laptop terlengkap dengan harga terjangkau.',
                'description_en' => 'The most complete center for electronics, cellphones, and laptops at affordable prices.',
                'description_ko' => '저렴한 가격의 전자제품, 휴대폰, 노트북 센터.',
                'description_zh' => '价格实惠的电子产品、手机和笔记本电脑中心。',
            ],

            // === Souvenir Shops ===
            ['category_key' => 'souvenir', 'sort_order' => 1,
                'title' => 'Grand Merciful Building', 'title_en' => 'Grand Merciful Building', 'title_ko' => '그랜드 머시풀 빌딩', 'title_zh' => '大仁慈大厦',
                'description' => 'Toko oleh-oleh terbesar dan terlengkap, dari kerajinan tangan hingga makanan khas.',
                'description_en' => 'The largest and most comprehensive gift shop, from handicrafts to special food.',
                'description_ko' => '수공예품부터 특산물까지, 가장 크고 포괄적인 기념품 가게.',
                'description_zh' => '最大最全面的礼品店，从手工艺品到特色食品。',
            ],
            ['category_key' => 'souvenir', 'sort_order' => 2,
                'title' => 'UD Kawanua', 'title_en' => 'UD Kawanua', 'title_ko' => 'UD 카와누아', 'title_zh' => 'UD卡瓦努阿',
                'description' => 'Toko oleh-oleh khas sejak 1989, menyediakan Klappertaart dan berbagai kue Manado.',
                'description_en' => 'Typical Manado souvenir shop since 1989, providing Klappertaart and various cakes.',
                'description_ko' => '1989년부터 운영된 마나도 특산 기념품 가게.',
                'description_zh' => '自1989年以来的美纳多特色纪念品商店。',
            ],

            // === Minahasa ===
            ['category_key' => 'minahasa', 'sort_order' => 1,
                'title' => 'Desa Tinoor', 'title_en' => 'Tinoor Village', 'title_ko' => '티누르 마을', 'title_zh' => '蒂努尔村',
                'description' => 'Tempat pengrajin bambu dan kayu di sepanjang jalan menuju Tomohon.',
                'description_en' => 'Place for bamboo and wood craftsmen along the way to Tomohon.',
                'description_ko' => '토모혼으로 가는 길에 있는 대나무와 목공예 장인 마을.',
                'description_zh' => '通往托莫洪途中的竹木工匠之地。',
            ],
            ['category_key' => 'minahasa', 'sort_order' => 2,
                'title' => 'Pasar Beriman Tomohon', 'title_en' => 'Tomohon Extreme Market', 'title_ko' => '토모혼 익스트림 시장', 'title_zh' => '托莫洪极端市场',
                'description' => 'Pasar tradisional terbesar di Minahasa, terkenal dengan bagian daging ekstrimnya.',
                'description_en' => 'The largest traditional market in Minahasa, famous for its extreme meat section.',
                'description_ko' => '미나하사에서 가장 큰 전통 시장으로, 극한의 고기 코너로 유명합니다.',
                'description_zh' => '米纳哈萨最大的传统市场，以其极端的肉类区域而闻名。',
            ],
        ];

        foreach ($shoppingItems as $item) {
            TravelInfoItem::create(array_merge($item, [
                'type' => 'shopping',
                'is_active' => true,
            ]));
        }

        // ============================================================
        // GUIDE (type: guide) — 20 items, no category_key
        // ============================================================
        $guideItems = [
            [
                'title' => 'Pulau Bunaken & Siladen',
                'title_en' => 'Bunaken & Siladen Island',
                'title_ko' => '부나켄 & 실라덴 섬',
                'title_zh' => '布纳肯和西拉登岛',
                'description' => 'Taman Nasional Laut Bunaken memiliki biodiversitas laut tertinggi di dunia. Waktu terbaik berkunjung adalah Mei - Agustus.',
                'description_en' => 'Bunaken National Marine Park has some of the highest levels of marine biodiversity in the world. Best time: May - August.',
                'description_ko' => '부나켄 국립 해양 공원은 세계에서 가장 높은 해양 생물 다양성을 보유하고 있습니다.',
                'description_zh' => '布纳肯国家海洋公园拥有世界上最高的海洋生物多样性。最佳时间：5月至8月。',
                'sort_order' => 1,
            ],
            [
                'title' => 'Selat Lembeh',
                'title_en' => 'Lembeh Straits',
                'title_ko' => '렘베 해협',
                'title_zh' => '蓝碧海峡',
                'description' => 'Surga bagi pecinta fotografi makro bawah laut dengan berbagai biota unik dan langka.',
                'description_en' => 'A real macro paradise and a great place to do scuba diving with rare and special critters.',
                'description_ko' => '희귀하고 특별한 생물과 함께 스쿠버 다이빙을 할 수 있는 매크로 천국.',
                'description_zh' => '真正的微距天堂，是与稀有特殊生物一起潜水的好地方。',
                'sort_order' => 2,
            ],
            [
                'title' => 'Klenteng Ban Hin Kiong',
                'title_en' => 'Chinese Temple Ban Hin Kiong',
                'title_ko' => '반힌키옹 사원',
                'title_zh' => '万兴宫',
                'description' => 'Klenteng tertua di Indonesia Timur, pusat perayaan festival Cap Go Meh yang meriah.',
                'description_en' => 'The oldest Buddhist temple in Eastern Indonesia, center of the attractive annual festival Toa Peh Kong.',
                'description_ko' => '인도네시아 동부에서 가장 오래된 불교 사원.',
                'description_zh' => '印度尼西亚东部最古老的佛教寺庙，每年举办盛大的元宵节庆典。',
                'sort_order' => 3,
            ],
            [
                'title' => 'Danau Linow',
                'title_en' => 'Linow Lake',
                'title_ko' => '리노우 호수',
                'title_zh' => '利诺湖',
                'description' => 'Danau unik yang warnanya bisa berubah-ubah, tempat yang sangat tenang untuk bersantai.',
                'description_en' => 'A unique lake where the waters can change colors between blue, green, and red. Perfect for relaxing.',
                'description_ko' => '물 색깔이 파란색, 초록색, 빨간색으로 변하는 독특한 호수.',
                'description_zh' => '一个独特的湖泊，湖水颜色会在蓝色、绿色和红色之间变化。',
                'sort_order' => 4,
            ],
            [
                'title' => 'Cagar Alam Tangkoko',
                'title_en' => 'Tangkoko Nature Reserve',
                'title_ko' => '탕코코 자연보호구역',
                'title_zh' => '坦科科自然保护区',
                'description' => 'Rumah bagi Tarsius (primata terkecil di dunia) dan monyet hitam Sulawesi (Yaki).',
                'description_en' => 'Home to Tarsiers (the smallest primate in the world) and the endemic Sulawesi black apes.',
                'description_ko' => '세계에서 가장 작은 영장류인 안경원숭이와 술라웨시 흑원숭이의 서식지.',
                'description_zh' => '世界上最小的灵长类动物眼镜猴和苏拉威西黑猿的家园。',
                'sort_order' => 5,
            ],
            [
                'title' => 'Danau Tondano',
                'title_en' => 'Tondano Lake',
                'title_ko' => '톤다노 호수',
                'title_zh' => '通达诺湖',
                'description' => 'Danau terluas di Sulawesi Utara dengan pemandangan pegunungan dan restoran apung yang lezat.',
                'description_en' => 'A famous tourist destination located 600 meters above sea level with awesome mountain views.',
                'description_ko' => '해발 600미터에 위치한 유명한 관광지로, 멋진 산 전망을 자랑합니다.',
                'description_zh' => '北苏拉威西最大的湖泊，拥有山景和美味的水上餐厅。',
                'sort_order' => 6,
            ],
            [
                'title' => 'Air Terjun Tunan',
                'title_en' => 'Waterfall Tunan',
                'title_ko' => '투난 폭포',
                'title_zh' => '图南瀑布',
                'description' => 'Air terjun alami setinggi 86 meter yang dikelilingi hutan rimbun di Minahasa Utara.',
                'description_en' => 'A beautiful 86-meter high waterfall surrounded by natural forest in North Minahasa.',
                'description_ko' => '북미나하사 자연림으로 둘러싸인 86미터 높이의 아름다운 폭포.',
                'description_zh' => '北米纳哈萨自然森林中一座美丽的86米高瀑布。',
                'sort_order' => 7,
            ],
            [
                'title' => 'Pagoda Ekayana',
                'title_en' => 'Pagoda Ekayana',
                'title_ko' => '에카야나 탑',
                'title_zh' => '一乘宝塔',
                'description' => 'Vihara indah dengan arsitektur megah dan pemandangan Gunung Lokon.',
                'description_en' => 'A unique temple with many sculptures and a large Pagoda Tower overlooking Mount Lokon.',
                'description_ko' => '많은 조각상과 로콘 산이 내려다보이는 큰 탑이 있는 독특한 사원.',
                'description_zh' => '拥有众多雕塑和俯瞰洛肯山的大宝塔的独特寺庙。',
                'sort_order' => 8,
            ],
            [
                'title' => 'Makatete Hills',
                'title_en' => 'Makatete Hills',
                'title_ko' => '마카테테 힐스',
                'title_zh' => '马卡特特山',
                'description' => 'Bukit dengan pemandangan Kota Manado yang spektakuler, cocok untuk melihat matahari terbenam.',
                'description_en' => 'A hilltop area with spectacular views of Manado City and the surrounding islands.',
                'description_ko' => '마나도 시와 주변 섬의 장관을 감상할 수 있는 언덕.',
                'description_zh' => '山顶区域，可以欣赏到美纳多市和周围岛屿的壮观景色。',
                'sort_order' => 9,
            ],
            [
                'title' => 'Patung Yesus (Pulau Lembeh)',
                'title_en' => 'Statue of Jesus (Lembeh)',
                'title_ko' => '예수 동상 (렘베)',
                'title_zh' => '耶稣雕像（蓝碧岛）',
                'description' => 'Monumen Yesus yang berdiri megah di Pulau Lembeh, mirip dengan patung di Rio de Janeiro.',
                'description_en' => 'Lembeh Island stands the Brazilian-style twin Statue of Jesus Blessing.',
                'description_ko' => '렘베 섬에 브라질 스타일의 예수 축복 쌍둥이 동상이 서 있습니다.',
                'description_zh' => '蓝碧岛上矗立着巴西风格的耶稣祝福双子雕像。',
                'sort_order' => 10,
            ],
            [
                'title' => 'Monumen Trikora',
                'title_en' => 'Trikora Monument',
                'title_ko' => '트리코라 기념비',
                'title_zh' => '三角勋章纪念碑',
                'description' => 'Monumen bersejarah peringatan pembebasan Irian Barat yang terletak di Pulau Lembeh.',
                'description_en' => 'A monument erected to commemorate the action of Three People\'s Commands in Lembeh Island.',
                'description_ko' => '렘베 섬에 있는 삼인민 명령 기념비.',
                'description_zh' => '为纪念蓝碧岛上的三人民指挥行动而建立的纪念碑。',
                'sort_order' => 11,
            ],
            [
                'title' => 'Alamanda Chapel',
                'title_en' => 'Alamanda Chapel',
                'title_ko' => '알라만다 채플',
                'title_zh' => '阿拉曼达教堂',
                'description' => 'Kapel indah di dataran tinggi Tomohon dengan latar belakang Gunung Lokon.',
                'description_en' => 'Also known as Chapel Mother of Mary, located on the highland of Tomohon with peaceful retreats.',
                'description_ko' => '토모혼 고원에 위치한 평화로운 피정지.',
                'description_zh' => '位于托莫洪高原上的美丽教堂，以洛肯山为背景。',
                'sort_order' => 12,
            ],
            [
                'title' => 'Bukit Kasih',
                'title_en' => 'The Hill of Love',
                'title_ko' => '사랑의 언덕',
                'title_zh' => '爱之丘',
                'description' => 'Pusat spiritual di mana rumah ibadah dari 5 agama berdiri berdampingan di satu bukit.',
                'description_en' => 'A spiritual center where 5 different religious houses of worship stand together on one hill.',
                'description_ko' => '5개의 다른 종교 예배당이 하나의 언덕에 함께 서 있는 영적 중심지.',
                'description_zh' => '一个精神中心，五种不同宗教的礼拜堂矗立在同一座山丘上。',
                'sort_order' => 13,
            ],
            [
                'title' => 'Gunung Mahawu',
                'title_en' => 'Mount Mahawu',
                'title_ko' => '마하우 산',
                'title_zh' => '马哈武火山',
                'description' => 'Gunung berapi yang mudah didaki dengan pemandangan kawah dan Kota Tomohon yang menakjubkan.',
                'description_en' => 'An adventure trekking to the craters of Mount Mahawu with awesome steaming crater lakes view.',
                'description_ko' => '증기가 나는 분화구 호수의 멋진 전망과 함께 마하우 산 분화구 트레킹.',
                'description_zh' => '可以轻松攀登的火山，拥有令人惊叹的火山口和托莫洪市景观。',
                'sort_order' => 14,
            ],
            [
                'title' => 'Desa Woloan',
                'title_en' => 'Woloan Village',
                'title_ko' => '월로안 마을',
                'title_zh' => '沃罗安村',
                'description' => 'Pusat industri rumah panggung kayu tradisional Minahasa yang bisa dibongkar pasang.',
                'description_en' => 'Center for traditional Minahasan knockdown wooden houses industry.',
                'description_ko' => '전통 미나하사 분해 조립식 목조 주택 산업의 중심지.',
                'description_zh' => '传统米纳哈萨可拆卸木屋产业中心。',
                'sort_order' => 15,
            ],
            [
                'title' => 'Waruga (Makam Batu)',
                'title_en' => 'WARUGA (Stone Graves)',
                'title_ko' => '와루가 (돌무덤)',
                'title_zh' => '瓦鲁加（石棺）',
                'description' => 'Situs purbakala makam batu leluhur Minahasa yang berasal dari zaman Megalitikum.',
                'description_en' => 'Ancient stone graves or sarcophagi of Minahasan ancestors dating back to the Megalithic Age.',
                'description_ko' => '거석 시대로 거슬러 올라가는 미나하사 조상들의 고대 석관.',
                'description_zh' => '可追溯到巨石时代的米纳哈萨祖先古代石棺。',
                'sort_order' => 16,
            ],
            [
                'title' => 'Rafting Timbukar',
                'title_en' => 'Rafting Timbukar',
                'title_ko' => '팀부카르 래프팅',
                'title_zh' => '廷布卡尔漂流',
                'description' => 'Petualangan arung jeram yang menantang dan seru di Sungai Timbukar, Sonder.',
                'description_en' => 'One of the most spectacular and exciting adventure sports in North Sulawesi.',
                'description_ko' => '북술라웨시에서 가장 장관이고 흥미진진한 모험 스포츠 중 하나.',
                'description_zh' => '北苏拉威西最壮观、最令人兴奋的冒险运动之一。',
                'sort_order' => 17,
            ],
            [
                'title' => 'Golf Resort Kawanua',
                'title_en' => 'Golf Resort Kawanua',
                'title_ko' => '카와누아 골프 리조트',
                'title_zh' => '卡瓦努阿高尔夫度假村',
                'description' => 'Resor golf internasional dengan pemandangan Gunung Klabat yang megah.',
                'description_en' => 'International golf resort with a great view of Klabat Mountain near the airport.',
                'description_ko' => '공항 근처 클라바트 산의 멋진 전망이 있는 국제 골프 리조트.',
                'description_zh' => '国际高尔夫度假村，可欣赏机场附近克拉巴特山的美景。',
                'sort_order' => 18,
            ],
            [
                'title' => 'Museum Negeri',
                'title_en' => 'The Provincial Museum',
                'title_ko' => '북술라웨시 박물관',
                'title_zh' => '省博物馆',
                'description' => 'Pusat sejarah dan budaya Sulawesi Utara yang menyimpan berbagai artefak berharga.',
                'description_en' => 'Houses historical, cultural and other artefacts from several Indonesian ethnic groups.',
                'description_ko' => '여러 인도네시아 민족의 역사적, 문화적 유물을 소장하고 있습니다.',
                'description_zh' => '收藏了来自印度尼西亚多个民族的历史和文化文物。',
                'sort_order' => 19,
            ],
            [
                'title' => 'Goa Jepang',
                'title_en' => 'Japanese Cave',
                'title_ko' => '일본 동굴',
                'title_zh' => '日本洞穴',
                'description' => 'Situs bersejarah peninggalan Perang Dunia II yang terletak di antara Kawangkoan dan Kiawa.',
                'description_en' => 'Historical site built during World War II by the Japanese between Kawangkoan and Kiawa.',
                'description_ko' => '카왕코안과 키아와 사이에 일본이 제2차 세계대전 중 건설한 역사적 유적지.',
                'description_zh' => '二战期间日本在Kawangkoan和Kiawa之间建造的历史遗址。',
                'sort_order' => 20,
            ],
        ];

        foreach ($guideItems as $item) {
            TravelInfoItem::create(array_merge($item, [
                'type' => 'guide',
                'category_key' => null,
                'is_active' => true,
            ]));
        }

        $this->command->info('✅ TravelInfoItem seeder completed!');
        $this->command->info('   → Culture: ' . count($cultureItems) . ' items');
        $this->command->info('   → Food: ' . count($foodItems) . ' items');
        $this->command->info('   → Shopping: ' . count($shoppingItems) . ' items');
        $this->command->info('   → Guide: ' . count($guideItems) . ' items');
    }
}
